services:
  unisync-db:
    image: postgres:15-alpine
    container_name: unisync-db
    environment:
      POSTGRES_USER: unisync_user
      POSTGRES_PASSWORD: unisync_password
      POSTGRES_DB: unisync_metadata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unisync_user -d unisync_metadata"]
      interval: 5s
      timeout: 5s
      retries: 5

  unisync-api:
    build:
      context: .
      dockerfile: UniSync.Backend/Dockerfile
    container_name: unisync-api
    ports:
      - "5134:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=unisync-db;Port=5432;Database=unisync_metadata;Username=unisync_user;Password=unisync_password"
      Jwt__Key: "СуперСекретныйКлючДляUniSync2026_ДлиннойМинимум32Символа!"
    depends_on:
      unisync-db:
        condition: service_healthy

volumes:
  pgdata:
